[features]
seeds = false
[programs.devnet]
myepicproject = "5akERpkEyZvwv24amdtwke5kHnhmiDKEVvYraaZ6pVTS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rohit/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
